spring:
  profiles:
    active: @spring.profiles.active@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # springboot升级2.6.0导致的

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml

jwt:
  #加密密钥
  secret: f4e2e52034348f86b67cde581c0f9eb5
  #token有效期，7天，单位秒
  expire: 604800
  header: Authorization




