spring:
  profiles:
    active: @spring.profiles.active@

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml

shiro-redis:
  enable: true
  redis-manager:
    host: 127.0.0.1:6379

jwt:
  #加密密钥
  secret: f4e2e52034348f86b67cde581c0f9eb5
  #token有效期，7天，单位秒
  expire: 604800
  header: Authorization




