server:
  port: 8888

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.30:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: lkc8658759@!

  redis:
    host: 127.0.0.1
    port: 6379
    password:

logging:
  config: classpath:log4j2-prd.xml