spring:
  profiles:
    active: @spring.profiles.active@

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml




